name: CI Pipeline - DeveloperEvaluation

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Test
      run: cd ./backend && chmod +x ./coverage-report.sh && ./coverage-report.sh